/**
 * Abstract base class for all DeclareUI code generators.
 */

import type { ComponentAST, Expression, GeneratedFile, PropDefinition } from '../ast/types.js';

/**
 * Base generator class that all target generators extend.
 */
export abstract class BaseGenerator {
  /** Generate output files from a ComponentAST */
  abstract generate(ast: ComponentAST): GeneratedFile[];

  /** Map DeclareUI prop type to target language type */
  protected mapPropType(prop: PropDefinition): string {
    switch (prop.type) {
      case 'string':
        return 'string';
      case 'number':
        return 'number';
      case 'boolean':
        return 'boolean';
      case 'enum':
        return prop.values?.map((v) => `'${v}'`).join(' | ') ?? 'string';
      case 'object':
        return 'Record<string, unknown>';
      case 'array':
        return 'unknown[]';
      case 'function':
        return '(...args: unknown[]) => unknown';
      default:
        return 'unknown';
    }
  }

  /**
   * Transform a DeclareUI expression to target code.
   * Default: replace $props.x with x, $state.x with stateVar.
   */
  protected transformExpression(expr: Expression | string): string {
    const raw = typeof expr === 'string' ? expr : expr.raw;
    return raw
      .replace(/\$props\.(\w+)/g, '$1')
      .replace(/\$state\.(\w+)/g, '$1')
      .replace(/\$event/g, 'event');
  }

  /** Get the generated file header comment */
  protected getHeader(): string {
    return '// Generated by DeclareUI — do not edit manually';
  }
}
