import { describe, it, expect } from 'vitest';
import { parseComponent } from '../parser/yaml-parser.js';
import { validateComponent } from '../validator/index.js';
import { ReactGenerator } from './react.js';

const BUTTON_YAML = `
component: Button
version: "1.0.0"
description: "Reusable button with variants and states"

props:
  variant:
    type: enum
    values: [primary, secondary, ghost, danger]
    default: primary
  size:
    type: enum
    values: [sm, md, lg]
    default: md
  disabled:
    type: boolean
    default: false
  loading:
    type: boolean
    default: false
  label:
    type: string
    required: true

state:
  isPressed:
    type: boolean
    initial: false

events:
  click:
    payload:
      originalEvent: MouseEvent

template:
  tag: button
  attrs:
    type: button
    disabled: "$props.disabled || $props.loading"
  classes:
    base: "inline-flex items-center justify-center"
    variants:
      variant:
        primary: "bg-blue-600 text-white"
        secondary: "bg-gray-100"
    conditionals:
      - when: "$props.disabled"
        add: "opacity-50"
  on:
    click: |
      if (!$props.disabled && !$props.loading) {
        $emit('click', { originalEvent: $event });
      }
    mousedown: "$state.isPressed = true"
    mouseup: "$state.isPressed = false"
  children:
    - when: "$props.loading"
      tag: span
      classes: "animate-spin"
    - tag: span
      content: "$props.label"

slots:
  default:
    description: "Custom content"
    fallback: "$props.label"
`;

describe('React Generator', () => {
  const generator = new ReactGenerator();

  function generateButton() {
    const raw = parseComponent(BUTTON_YAML);
    const ast = validateComponent(raw);
    return generator.generate(ast);
  }

  it('generates component and cn utility files', () => {
    const files = generateButton();
    expect(files).toHaveLength(2);
    expect(files[0].filename).toBe('button.tsx');
    expect(files[1].filename).toBe('cn.ts');
  });

  it('includes Generated by DeclareUI header', () => {
    const files = generateButton();
    expect(files[0].content).toContain('Generated by DeclareUI');
  });

  it('includes forwardRef', () => {
    const files = generateButton();
    expect(files[0].content).toContain('forwardRef');
  });

  it('generates ButtonProps interface', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toContain('export interface ButtonProps');
    expect(content).toContain('label: string');
  });

  it('generates enum type as union', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toMatch(/'primary'\s*\|\s*'secondary'\s*\|\s*'ghost'\s*\|\s*'danger'/);
  });

  it('generates event callback prop', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toContain('onClick?:');
  });

  it('includes useState hook', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toContain('useState');
    expect(content).toContain('isPressed');
  });

  it('uses cn() for class composition', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toContain('cn(');
  });

  it('includes proper React imports', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toContain("from 'react'");
    expect(content).toContain('forwardRef');
    expect(content).toContain('useState');
  });

  it('sets displayName', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toContain("Button.displayName = 'Button'");
  });

  it('generates children prop for default slot', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toContain('children?: React.ReactNode');
  });

  it('generates cn utility with proper content', () => {
    const files = generateButton();
    const cnContent = files[1].content;
    expect(cnContent).toContain('export function cn');
    expect(cnContent).toContain('ClassValue');
  });
});
