import { describe, it, expect } from 'vitest';
import { parseComponent } from '../parser/yaml-parser.js';
import { validateComponent } from '../validator/index.js';
import { WCGenerator } from './wc.js';

const BUTTON_YAML = `
component: Button
version: "1.0.0"

props:
  variant:
    type: enum
    values: [primary, secondary]
    default: primary
  disabled:
    type: boolean
    default: false
  label:
    type: string
    required: true

state:
  isPressed:
    type: boolean
    initial: false

events:
  click:
    payload:
      originalEvent: MouseEvent

template:
  tag: button
  attrs:
    type: button
  classes:
    base: "px-4 py-2"
  on:
    click: "$emit('click', { originalEvent: $event })"
  children:
    - tag: span
      content: "$props.label"
`;

describe('Web Components Generator', () => {
  const generator = new WCGenerator();

  function generateButton() {
    const raw = parseComponent(BUTTON_YAML);
    const ast = validateComponent(raw);
    return generator.generate(ast);
  }

  it('generates a single .ts file', () => {
    const files = generateButton();
    expect(files).toHaveLength(1);
    expect(files[0].filename).toBe('button.ts');
    expect(files[0].language).toBe('typescript');
  });

  it('includes Generated by DeclareUI header', () => {
    const files = generateButton();
    expect(files[0].content).toContain('Generated by DeclareUI');
  });

  it('extends HTMLElement', () => {
    const files = generateButton();
    expect(files[0].content).toContain('extends HTMLElement');
  });

  it('defines observedAttributes', () => {
    const files = generateButton();
    const content = files[0].content;
    expect(content).toContain('static observedAttributes');
    expect(content).toContain("'variant'");
    expect(content).toContain("'disabled'");
    expect(content).toContain("'label'");
  });

  it('attaches shadow DOM', () => {
    const files = generateButton();
    expect(files[0].content).toContain("attachShadow({ mode: 'open' })");
  });

  it('implements connectedCallback', () => {
    const files = generateButton();
    expect(files[0].content).toContain('connectedCallback()');
  });

  it('implements attributeChangedCallback', () => {
    const files = generateButton();
    expect(files[0].content).toContain('attributeChangedCallback(');
  });

  it('registers custom element with dui- prefix', () => {
    const files = generateButton();
    expect(files[0].content).toContain("customElements.define('dui-button'");
  });

  it('uses DuiButton class name', () => {
    const files = generateButton();
    expect(files[0].content).toContain('class DuiButton extends HTMLElement');
  });

  it('includes private state', () => {
    const files = generateButton();
    expect(files[0].content).toContain('#state');
    expect(files[0].content).toContain('isPressed');
  });
});
